### ISSUE TITLE
Item Outputs Not Increased + Laggy Machine Processing

### ISSUE THREAD

**Issue by TheGameAce** [starforcraft/Centrifuge-Tiers-Reproduced#10]
Latest 1.20.1 Forge.

So far it doesn't seem that outputs are higher. With some combs I still see minimum outputs when giving an output, & I never see values that seem to match up to the related centrifuge. On a single hive system with a Nuclear centrifuge for an example, I'm observing Experience Comb Blocks only outputting 400mb at a time, which is the default value.

Processing times are also not that fast, much less multiple times faster than the heated centrifuge. It almost looks like the system is laggy trying to get up to speed. Which isn't necessarily bad presently, since even Mekanism's ultimate pipes + transporters can't keep up with the output load & even struggle with the input a bit.

Still quite useful when you have dozens of hives producing enormous amounts of material, but the expense is wild when the main features aren't fully functional.

In later addendum now, Spark profiler also shows severe lag issues with this mod that seems to stem from checking for valid items.

**Comment by starforcraft** [comment]
1.20.1 is not supported anymore
