### ISSUE TITLE
Crashing When Placing Centrifuge Controller

### ISSUE THREAD

**Issue by TwistedKindn3ss** [starforcraft/Centrifuge-Tiers-Reproduced#11]
Hello, not sure if it's because Im playing the ATM10 Modpack, but when I add this mod into it and try to place a controller down, the world/game crashes. I've tried this with different tier controllers and still same outcome. I even try to build a 9x9 block minus one for controller and it still crashes.

I've attached a crash log that I get when it occurs. Any help/pointers would be great.

Ty!

[crash-2024-11-15_19.45.27-client.txt](https://github.com/user-attachments/files/17782749/crash-2024-11-15_19.45.27-client.txt)

Edit: Forgot to add that I am using the latest version on 1.21.1. Additionally if I downgrade the file to a previous version, placing controllers works.

**Comment by starforcraft** [comment]
You have to update Productive Bees
