### ISSUE TITLE
Crash with nuclear cenrifuge

### ISSUE THREAD

**Issue by Eq1s** [starforcraft/Centrifuge-Tiers-Reproduced#4]
Idk what exact wrong, but looks like problem with input comb slots.

[crash-2023-09-12_19.08.07-server.txt](https://github.com/starforcraft/Centrifuge-Tiers-Reproduced/files/12587420/crash-2023-09-12_19.08.07-server.txt)

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/centrifuge-tiers-reproduced/files/4763496
