### ISSUE TITLE
Centrifuges much slower in latest update

### ISSUE THREAD

**Issue by contra1337** [starforcraft/Centrifuge-Tiers-Reproduced#6]
I recently updated from [1.20.1-1.2.jar](https://legacy.curseforge.com/minecraft/mc-mods/centrifuge-tiers-reproduced/files/4763496) to [1.20.1-1.3.jar](https://legacy.curseforge.com/minecraft/mc-mods/centrifuge-tiers-reproduced/files/4870953) because I saw there were fixes for issues I was having (only running with first slot, and crashing)

Thanks for addressing those! I had to restore a backup of my world due to the crashing previously, so I'm glad its fixed

After updating to 1.3 however, the Nuclear and Cosmic centrifuges I was using are dramatically slower. I tested all of the tiers with 4x speed upgrades, and it seems like Cosmic, Nuclear, and High End are all affected by this. They are all actually slower than the original Heated Centrifuge for a stack of combs (just into the first slot, not split up). A Powered Centrifuge (tier below heated) was faster than the High End... and even the Creative one doesn't seem to be as fast as the Nuclear was in the 1.2 version

I am wondering if this was changed intentionally and the current behavior is supposed to be correct? Or is this slow-down a bug? the only reason for me to use the higher tiers in this version now is for more input slots and the output multiplier, but I'd probably just make more bees and use more heated centrifuge instead if this is intended

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/centrifuge-tiers-reproduced/files/5034071

**Comment by contra1337** [comment]
Working much faster now, thanks for looking into it!
