### ISSUE TITLE
server crash after update Productive Bees

### ISSUE THREAD

**Issue by ptk2003** [starforcraft/Centrifuge-Tiers-Reproduced#7]
After update from PB 1.20.1-12.2.14 to .15 server side crashed when world loaded (with exists centrifuges from CTR).

PB 1.20.1-12.2.15
CTR 1.20.1-1.3
forge 47.2.19
[crash-2024-01-14_18.01.12-server.txt](https://github.com/starforcraft/Centrifuge-Tiers-Reproduced/files/13933162/crash-2024-01-14_18.01.12-server.txt)

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/centrifuge-tiers-reproduced/files/5034071

**Comment by ptk2003** [comment]
now not working. input ingredients placed in output buffer (manually or any cables) and input buffer for honey comb not accessible (manually or any cables) 
and little glitch (it was before update): in GUI show 0 energy
config reset, centrifuge replace.
![2024-01-15_21 51 47](https://github.com/starforcraft/Centrifuge-Tiers-Reproduced/assets/28514017/5c5c6116-06b2-4741-a99e-b8967dda8595)
![2024-01-15_21 52 08](https://github.com/starforcraft/Centrifuge-Tiers-Reproduced/assets/28514017/be27a962-eac9-45f6-8284-dd910f4f400a)

**Comment by starforcraft** [comment]
Hopefully this is fixed now: https://legacy.curseforge.com/minecraft/mc-mods/centrifuge-tiers-reproduced/files/5034794

**Comment by contra1337** [comment]
1.4.1 does fix the input slot issue for me at least

**Comment by ptk2003** [comment]
I can check it 16/01/24 after 21:00 UTC

**Comment by ptk2003** [comment]
now work fine, thank you.

little glitch:
'waila' see not accesible in gui 3x slots, they can be filled cables but can not be extracted.
in gui nothing not see
![2024-01-16_21 54 59](https://github.com/starforcraft/Centrifuge-Tiers-Reproduced/assets/28514017/6bda2032-a795-4171-b295-e94df478b09c)
![2024-01-16_21 55 05](https://github.com/starforcraft/Centrifuge-Tiers-Reproduced/assets/28514017/816bfced-62b9-4680-8dd1-6f175adbc713)
