### ISSUE TITLE
Breaking Change with Productive Bees v2.3.0

### ISSUE THREAD

**Issue by DragonS0u1623** [starforcraft/Centrifuge-Tiers-Reproduced#8]
LJ split common functionality off into a library mod in v2.3.0, meaning the latest version of Productive Bees is incompatible with Centrifuge Tiers. Just wanted to bring attention to it in case the change goes under the radar for most.

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/centrifuge-tiers-reproduced/files/5120541
